name: Deployment App

on:
  push:
    branches:
      - master

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd pace-app/my-pages/
            sudo git pull origin master
            cd ..
            sudo docker compose up -d --build my-pages
            sudo docker ps
